TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += lakeshore372.db
DATA += lakeshore372.proto

#=======================================
include $(TOP)/configure/RULES
